/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddBookingInputDTO { 
    clientId?: string | null;
    entryDate: string;
    departureDate: string;
    totalPeople: number;
    requestCaptain?: boolean;
    boatIds?: Array<number> | null;
    serviceIds?: Array<number> | null;
    activityIds?: Array<number> | null;
}

